### ISSUE TITLE
set-output will be disabled

### ISSUE THREAD

**Issue by dennistruemper** [gacts/github-slug#48]
Hi @tarampampam, 

when I use your action I get a lot of warnings: `The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files.`

[This seems to be the code with need to change](https://github.com/gacts/github-slug/blob/master/src/index.js#L55)

[Here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) is some official stuff. Your action will stop working after May 2023, so no hurry.

Have a nice Weekend,
Dennis

**Comment by tarampampam** [comment]
Hi @dennistruemper!

Looks very strange... 9 days ago I have released an updated version (with a fresh [@actions/core](https://github.com/gacts/github-slug/commit/4fa676f0e6eddfac005a46b3d9d90018e2053ab5) version). Besides that, if you take a look on at any workflow run in this repo - there are no warnings:

![image](https://user-images.githubusercontent.com/7326800/200129563-dc3027ca-1a7f-41bc-a76c-5a9e69542a02.png)

**Comment by tarampampam** [comment]
Oh shit, I found the problem. For some unknown reason, the release workflow did not start. The latest release re-released, and all should be fine for now, check on your side, please.

**Comment by tarampampam** [comment]
Ping @dennistruemper

**Comment by dennistruemper** [comment]
No more warnings :-)
